# config.yml
particles:
  Jpsi:
    J: 1
    P: -1
    mass: 3.0969
  eta:
    J: 0
    P: -1
    mass: 0.5478
  Kp:
    J: 0
    P: -1
    mass: 0.4937
  Km:
    J: 0
    P: -1
    mass: 0.4937

data:
  dat_order: [Kp, Km, eta]
  data: ["/home/whitewash/pwa/toymc_test/root/data.dat"]
  phsp: ["/home/whitewash/pwa/toymc_test/root/phsp.dat"]
  #phsp: ["./phsp.dat"]

decay_chains:
  chain2:
    decay:
      - Jpsi: [Km, R_Kpeta]
      - R_Kpeta: [Kp, eta]
    R_Kpeta:
      #- [J: 1, P: -1]: [K1_1680p]
      #- [J: 2, P: 1]: [K2_1980p]
      - [J: 3, P: -1]: [K3_1780p]
      

resonances:
  K3_1780p:
    J: 3
    P: -1
    #model: BWR
    model: ONE
    parameters: [1.711, 0.333]
    tex: "K_{3}^{*+}(1780)"

  K2_1980p:
    J: 2
    P: 1
    model: BWR
    parameters: [2.0169, 0.2]

  K1_1680p:
    J: 1
    P: -1
    model: BWR
    parameters: [1.718, 0.32]
    tex: "K_{1}^{*+}(1680)"
