# config.yml
Particles:
  Jpsi:
    J: 1
    P: -1
    mass: 3.0969
    tex: ['J/#psi']
  eta:
    J: 0
    P: -1
    mass: 0.5478
    tex: ['#eta']
  Kp:
    J: 0
    P: -1
    mass: 0.4937
    tex: ['K^{+}']
  Km:
    J: 0
    P: -1
    mass: 0.4937
    tex: ['K^{-}']

Data:
  order: [Kp, Km, eta]
  # 使用dat文件
  data: [dat, "/file.dat"]
  phsp: [dat, "/file.dat"]
  bkg:  [dat, "/file.dat"]
  #bkg_weights: [dat, "/file.dat"]
  
  # 使用root文件 （TBranch名字与order中粒子名字顺序一致）
  # data: [ROOT, "/file.root", TTree, TBranch1, TBranch2, TBranch3, ...]
  # phsp: [ROOT, "/file.root", TTree, TBranch1, TBranch2, TBranch3, ...]
  # bkg:  [ROOT, "/file.root", TTree, TBranch1, TBranch2, TBranch3, ...]
  # bkg_weights: [ROOT, "/file.root", TTree, TBranch1(weight)]
  # 也可混合使用


DecayChains:
  chain1:
    decay:
      - Jpsi: [eta, R_KK]
      - R_KK: [Kp, Km]
    R_KK:
      - [J: 1, P: -1]: [phi1020, X1750, omega1420, phi1680, rho1900, omega2220, NR1_KK]
      - [J: 3, P: -1]: [omega3_1670, phi3_1850, rho3_2250, NR3_KK]
    legend: [R_KK, eta]

  chain2:
    decay:
      - Jpsi: [Km, R_Kpeta]
      - R_Kpeta: [Kp, eta]
    R_Kpeta:
      - [J: 1, P: -1]: [K1_1410, K1_1680, K2380]
    legend: ["R_Kpeta[0]", "^{*+}", "R_Kpeta[1]", Km]


  chain3:
    decay:
      - Jpsi: [Kp, R_Kmeta]
      - R_Kmeta: [Km, eta]
    R_Kmeta:
      - [J: 1, P: -1]: [K1_1410, K1_1680, K2380]
    legend: ["R_Kmeta[0]", "^{*-}", "R_Kmeta[1]", Kp]

Constraints:
  trans:
    - [chain2, chain3]: [[-1, -1]]
    # 顺序一样即可简写，否则一个一个写
    # - [chain2-R_Kpeta-K1_1410, chain3-R_Kmeta-K1_1410]: [[-1, -1]]

Resonances:
  phi1020:
    J: 1
    P: -1
    model: BWR
    parameters: [1.0195, 0.005] # [mass, width]
    tex: ["#phi(1020)"]

  NR1_KK:
    J: 1
    P: -1
    model: ONE
    parameters: [1.5]
    tex: ["NR_{1}(KK)"]
    
  K1_1410:
    J: 1
    P: -1
    model: BWR
    parameters: [1.414, 0.232]
    tex: ["K_{1}", "(1410)"]

  K1630:
    J: 1
    P: -1
    model: BWR
    parameters: [1.629, 0.016]
    tex: ["K_{1}", "(1630)"]

# 生成的root文件包含多个TDirectory和lengends。每个TDirectory包含多个直方图和xlabel, ylabel。
Plot:
  mass:
    - input: [Kp, Km]
      bins: 100
      range: [1.0, 2.6]
      display: ["M(K^{+}K^{-}) (GeV/c^{2})", "Events/16 MeV/c^{2}"]
    - input: [Kp, eta]
      bins: 100
      range: [1.0, 2.6]
      display: ["M(K^{+}#eta) (GeV/c^{2})", "Events/16 MeV/c^{2}"]
  cosbeta:
    - input: [[Jpsi], [Kp, Km], [Kp]]
      bins: 100
      range: [-1.0, 1.0]
      display: ["cos#beta(K^{+}K^{-})", "Events/0.02"]
  dalitz:
    - input: [[Kp, Km], [Kp, eta]]
      bins: [100, 100]
      range: [[1.0, 6.8], [1.0, 6.8]]
      display: ["M^{2}(K^{+}K^{-}) (GeV^{2}/c^{4})", "M^{2}(K^{+}#eta) (GeV^{2}/c^{4})"]
